### PR TITLE
Adding an alternative online tool

### PR DESCRIPTION
**Pull request by techsmartteam**
This tool offer an extensive report about word count in a given text.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Thanks @harryngh, but I don't think this is really relevant, WordCount is a plugin, that bridges the gap between copying and pasting content into a web service. What does @BoundInCode think?

**Comment by techsmartteam** [comment]
Thank you for your swift response.You're right it is not really relevant since this is a project for a plugin. However, your project and my project have some similarity. Users who are interested in the word count statistics might find the resource in my project useful. It is brought online and it works at client side without having to fetch the result from the server so users can easily access it. Would you please somehow refer it in your README.md description like the additional online resource or something like that? I would really appreciate it and I would like to work to improve this plugin as well.

**Comment by titoBouzout** [comment]
There is hundred of WordCount solutions, submit your site to a directory instead, such http://www.dmoz.org/

**Comment by techsmartteam** [comment]
There are many word count solutions but none of them give an extensive report with the readability report at the same time.

**Comment by titoBouzout** [comment]
Yes, that's true, I see your site has really nice features.

**Comment by titoBouzout** [comment]
It has problems with unicode :-P "¿cómo estás?" gives 4 words instead of 2.

**Comment by titoBouzout** [comment]
Oh I see there is a "Non-English" button, but still all the Word Count Statistics vanish :-)

**Pull request closed without merging**
