### PR TITLE
Update WordCount Regular Expression (second attempt)

### PR DESCRIPTION
**Pull request by techsmartteam**
After more time to consideration, I think this regular expression is better.

[edited title by tito]

### CODE REVIEW

**Comment by titoBouzout** [comment]
Please put to your pull request a descriptive title. Also, would help if you explain why do you think the regular expression is better, and also, put some examples, of both, the current one, and the proposed one. Please include different languages, because we are an international community.

**Comment by jbrooksuk** [comment]
Really we should add a few tests that can be ran against TravisCI automatically. I might investigate this later.

**Comment by leegrey** [comment]
Hi. I tried the regular expression, and it appears to resolve the original issue that I reported.  Regular expressions are not my strong point, so thanks for coming up with it. I appreciate it. :)

**Comment by titoBouzout** [comment]
The package has been update, I think it works correctly now, counting words.

**Pull request closed without merging**
