### PR TITLE
Added installation instructions.

### PR DESCRIPTION
**Pull request by ghcpuman902**

### CODE REVIEW

**Comment by titoBouzout** [comment]
Mmmh, adding the repository shouldn't be needed.

**Comment by titoBouzout** [comment]
https://github.com/wbond/package_control_channel/blob/master/repository/w.json#L311-L319

**Comment by FichteFoll** [comment]
```
## Installation

1. If you don't have it already, follow the instructions on [https://sublime.wbond.net/installation](https://sublime.wbond.net/installation) to install Package Control 2+.
2. In Sublime Text, press <kbd>Ctrl+Shift+P</kbd> (Win, Linux) or <kbd>⌘⇧p</kbd> (OS X) to open the command palette.
3. Choose `Package Control: Install Package`.
4. Select **WordCount**.
```

**Comment by ghcpuman902** [comment]
@FichteFoll  On my laptop there wasn't any option for me to select.
So should I say:" Select WordCount when available."?

**Comment by ghcpuman902** [comment]
You guys are being so scary and not friendly at all... : (

**Comment by titoBouzout** [comment]
I'm sorry, whatever puts you down, don't let these thing put you down. 

Package control requires restart, maybe that was the cause of the package not showing? Are you sure you are using ST3?

The merge is acceptable once we find the confusion here

**Comment by ghcpuman902** [comment]
@titoBouzout Sorry the options did appear after I removed WordCount and reinstalled it.

**Comment by jbrooksuk** [comment]
I'm sorry if we're not being friendly, we're most definitely not being cruel. Just giving you feedback :)

**Comment by ghcpuman902** [comment]
@jbrooksuk @titoBouzout It's alright I understand you want to get things done efficiently. Thank you.

**Comment by FichteFoll** [comment]
@ghcpuman902, sorry, I just prefer to do things directly in some cases, and making the adjustments myself was way quicker than pointing out the other things I noticed that @jbrooksuk didn't mention. (I hope you saw what I changed though. ;) )

By the way, the reason you didn't see the package initially was probably because you had it already installed. Package Control doesn't list installed packages (since you have them already), but I'm rather confused as to why it would work when adding the repository manually. Did you follow these steps youself or did you just guess it would be necessary?

**Comment by titoBouzout** [comment]
This has been merged in #33 Thank you!

**Comment by ghcpuman902** [comment]
@FichteFoll I did those steps myself. Cause "Install Package" for me, it sounds like you need to select a package file from your laptop and you said do not install manually so I thought "Enable Packages" will make more sense so I tried it first, which didn't work. Then the second option I decided to try was "Add Repository" which after that I thought to install added/loaded package should work so I clicked on "Install Packages" this time and it worked. Does this make sense to you?

**Comment by FichteFoll** [comment]
cc @wbond, do you have any idea?

**Comment by wbond** [comment]
@FichteFoll I just skimmed through the thread - not sure what the issue is.

I confirmed you can install it in ST3 and it is not available in ST2.

**Comment by FichteFoll** [comment]
@wbond, it appears to me that @ghcpuman902 was not able to install the package normally using "Install Package" (not sure if he had it installed already) but it worked after he added the repository url manually. Could there be an issue with that? If not, just forget about it.

Repo and package names are identical.

Edit: Btw, haven't seen you on IRC lately.

**Comment by wbond** [comment]
I'd need a debug log to see why it wasn't installing previously.

Yeah, I need to get on IRC – life has been crazy, good, but crazy.

**Pull request closed without merging**
