### PR TITLE
Updating contributors

### PR DESCRIPTION
**Pull request by techsmartteam**
#### Having contributed so far:
- Pointing out the incompleteness in dealing with tab separation in issue #16, proposing a pull #20 to generalize for all white-space characters. The pull is merged into the **st3** branch.
- Proposing a pull and working with the pull #19 to update the regular expression in capturing sentences.

### CODE REVIEW

**Comment by titoBouzout** [comment]
It would be nice if you can check the log also to see if we miss some other contributor.
PS: wrong branch, it should be st3

**Comment by techsmartteam** [comment]
I did some research and have added 3 more contributors + the links to the authors also.
PS: The incompleteness exists in the master branch also, right? So the contribution is one way or another affects the master branch, isn't it?

**Comment by jbrooksuk** [comment]
The master branch is for ST2.

**Comment by techsmartteam** [comment]
Well I see. But the contributors I listed in the last commit have contributed in this plugin in general :)

**Comment by titoBouzout** [comment]
OK, update contributors but on st3 branch. Thanks harryngh

**Comment by jbrooksuk** [comment]
@titoBouzout are you okay with the advertisement?

**Comment by techsmartteam** [comment]
Thank you too.

**Comment by titoBouzout** [comment]
Is not OK, we have a experience here of a user that tried hard to put a link in our readme.md for SEO purposes. 

Since the main intention of the contribution was to get the link, and not to improve the package, the suggestions were done without thinking to much, even going to incorrect paths of updating the master branch for contributions done in an unrelated branch: ST3. All of this taking and consuming some of the people time...

May entertainment for some, but frustrating, It finally got the point of doing an actual contribution, and I have no problem with putting links near to contributor names per request or suggestion..

**Comment by jbrooksuk** [comment]
Ok then :+1:

**Pull request closed without merging**
