### PR TITLE
Estimated Reading Time

### PR DESCRIPTION
**Pull request by jbrooksuk**
I've added an estimated reading time, on the basis that most people read at 200 WPM, although [Wikipedia](http://en.wikipedia.org/wiki/Words_per_minute#Reading_and_comprehension) says 250 for an average American.

### CODE REVIEW

**Comment by titoBouzout** [comment]
Ok!

Can you please add a preference for this and remove the file package-metadata.json

Thanks!

**Comment by jbrooksuk** [comment]
Sure.

**Comment by jbrooksuk** [comment]
Embarrassingly I don't know how to remove a file from a repository...

**Comment by titoBouzout** [comment]
git rm -r -f -- filename
- this removes the file from the respository and removes the file from the disk

git rm -r --cached -- filename
- To keep the file on disk but remove it from the repository

and commit again :)

**Comment by jbrooksuk** [comment]
I think that's done it!

**Comment by titoBouzout** [comment]
Interesting thanks!

A minor stylistic note: maybe we can remove the "," from the beginning, then looks more integrated with the "xxx words" message?

**Comment by titoBouzout** [comment]
An idea: Add a preference to control WPM value. then, non-English readers can tweak the value.

**Comment by jbrooksuk** [comment]
I can do that :)

**Pull request merged**
