### PR TITLE
Tweaks on aesthetics

### PR DESCRIPTION
**Pull request by yanokwa**
Great work on the WordCount plugin! I was playing with it a bit and ended up removing duplication of 'selected' wording. I'm using v2165 and it looked a bit weird.

I also didn't like the set_status prepending aesthetics. I think "Line #, Column #, Words #" would be much easier to read, so I've removed the live word count for now. I now use Select All to get word count of the document.

Thoughts?

### CODE REVIEW

**Comment by titoBouzout** [comment]
Hi there!

> I was playing with it a bit and ended up removing duplication of 'selected' wording. I'm using v2165 and it looked a bit weird.

Can you please explain what's weird?. The plugin shows a real time "word count" of the entire document and also shows a "word count on selections" Not sure what you mean.

> I also didn't like the set_status prepending aesthetics. I think "Line #, Column #, Words #" would be much easier to read

I don't like too. Unfortunately there is no way to change the ordering of the messages into the status bar.

> I now use Select All to get word count of the document.

Pull request and hacks are very welcome.. I can't accept yours because removes functionality, but I'm willing to help you to get what you want implemented done (via preferences for example) discussing in this thread.

Regards,

**Comment by yanokwa** [comment]
When I select one region, the status reads "1 word selected, 8 characters selected". It seems nicer to have it read "1 word, 8 characters selected"

When I select more regions, the status reads "3 words in 3 selections, 3 selection regions". It seems nicer to have it read "3 words in 3 selection regions"

As to my hacks, I'd love to work with you on doing this the right way. 

One approach would be to see if the Sublime folks would add a set_status(key,message,position) where position was before or after the stock messages? In the meanwhile, I agree that a preference for showing live count would be a great solution. If you describe how you'd like it implemented, glad to take a crack at it.

**Comment by titoBouzout** [comment]
> One approach would be to see if the Sublime folks would add a set_status(key,message,position) where position was before or after the stock messages?

Ok,  I see, is a little weird, I don't think that feature will be added to Sublime in a near future, then, I agree we can remove the display of the count of selections. Something such "2 words selected" will look nice. Can you please rewrite this pull request to remove just the count of selections? Keeping the live count.

About removing the live count. I see something like this.

Add a file "WordCount.sublime-settings" with content

```
{
"enable_live_count": true
}
```

( enabled by default because the original purpose of this plugin is to show a live count )

After the import statements, before the Class you can load the preference by calling

```
s = sublime.load_settings('WordCount.sublime-settings')
```

"s" will hold a preference object on wich you can request the value of "enable_live_count" by 

```
s.get('enable_live_count', True)
```

an on https://github.com/SublimeText/WordCount/blob/master/WordCount.py#L48 you can check if the value is True to run the counter.

## 

I will wait patiently for your pull request. Please take your time. Any question let me know. After the update, I want to change some things on logic I learned lately.

Regards

**Comment by yanokwa** [comment]
Take a look at https://github.com/yanokwa/WordCount/commit/d4f6fdcaa8bf0eb168a2ee917560703155b4f228. That what you had in mind for the first part?

As to live_count, I don't think putting a check at https://github.com/SublimeText/WordCount/blob/master/WordCount.py#L48 is ideal. The thread has to run sometime, right? Otherwise how will you display the count on selection?  

Maybe at https://github.com/SublimeText/WordCount/blob/master/WordCount.py#L68?

**Comment by titoBouzout** [comment]
Commit looks good. I'll prefer the mention of "selected" when a selection is used, like "48 words selected"

L48 is for counting in the document, L49 if for counting in the selections.
on L48 you can check the condition.

We should try to remove the count, instead of just hiding the message.

**Comment by yanokwa** [comment]
I've attached images of the two examples I referred to.

So for one region, you want "1 word, 8 characters selected"

For two regions, you want "3 words selected, 3 selection regions"

On Sun, Jan 15, 2012 at 14:58, tito
reply@reply.github.com
wrote:

**Comment by titoBouzout** [comment]
There is no images here!

**Comment by yanokwa** [comment]
http://cs.washington.edu/homes/yanokwa/tmp/two_regions.png
http://cs.washington.edu/homes/yanokwa/tmp/one_region.png

On Sun, Jan 15, 2012 at 15:15, tito
reply@reply.github.com
wrote:

**Comment by titoBouzout** [comment]
When you select for example:  two paragraphs ( not just words ) the message looks like:

"234 words in 2 selections, 2 selection regions"

you are proposing 
"234 words, 2 selection regions"

I suggest:
"234 words selected, 2 selection regions"

Right? or I'm missing something

**Comment by yanokwa** [comment]
Alright, hope this looks OK. Still learning Python, Git and Sublime's API.

https://github.com/yanokwa/WordCount/commit/ece9719d9f5f0af0b1160cde524a691ac5129798

Had to add the global enable_live_count, or I got a UnboundLocalError.
Also had to erase_status or the word count stuck around after the
selection.

On Sun, Jan 15, 2012 at 15:32, tito
reply@reply.github.com
wrote:

**Comment by titoBouzout** [comment]
Ok looks good ! 

I think the "if enable_live_count" should be moved one line below :), then the else is not executed.

Regards,

**Comment by yanokwa** [comment]
This what you had in mind?

```
if len(sel) == 1 and sel[0].empty():
    if enable_live_count:
        WordCountThread(view, [view.substr(sublime.Region(0, view.size()))], False).start()
    else:
        view.erase_status('WordCount')
else:
    WordCountThread(view, [view.substr(sublime.Region(s.begin(), s.end())) for s in sel], True).start()
```

**Comment by titoBouzout** [comment]
Yes!

**Pull request closed without merging**
